set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN N11 [get_ports clk]
set_property IOSTANDARD LVCMOS18 [get_ports led*]
set_property PACKAGE_PIN C16 [get_ports led0]
set_property PACKAGE_PIN D15 [get_ports led1]
set_property PACKAGE_PIN D16 [get_ports led2]
set_property PACKAGE_PIN E16 [get_ports led3]
set_property PACKAGE_PIN P11 [get_ports sda]
set_property IOSTANDARD LVCMOS33 [get_ports sda]
set_property PACKAGE_PIN N13 [get_ports scl]
set_property IOSTANDARD LVCMOS33 [get_ports scl]

set_property IOSTANDARD LVCMOS18 [get_ports hd*]
set_property PACKAGE_PIN B16 [get_ports hdclk]
set_property PACKAGE_PIN B14 [get_ports hdde]
set_property PACKAGE_PIN B15 [get_ports hdvs]
set_property PACKAGE_PIN A15 [get_ports hdhs]
set_property PACKAGE_PIN A14 [get_ports {hddat[0]}]
set_property PACKAGE_PIN A13 [get_ports {hddat[1]}]
set_property PACKAGE_PIN B12 [get_ports {hddat[2]}]
set_property PACKAGE_PIN A12 [get_ports {hddat[3]}]
set_property PACKAGE_PIN B11 [get_ports {hddat[4]}]
set_property PACKAGE_PIN B10 [get_ports {hddat[5]}]
set_property PACKAGE_PIN A10 [get_ports {hddat[6]}]
set_property PACKAGE_PIN B9 [get_ports {hddat[7]}]
set_property PACKAGE_PIN A9 [get_ports {hddat[8]}]
set_property PACKAGE_PIN C8 [get_ports {hddat[9]}]
set_property PACKAGE_PIN A8 [get_ports {hddat[10]}]
set_property PACKAGE_PIN D8 [get_ports {hddat[11]}]
set_property PACKAGE_PIN C11 [get_ports hdmclk]
set_property PACKAGE_PIN C13 [get_ports hdsclk]
set_property PACKAGE_PIN C14 [get_ports hdlrclk]
set_property PACKAGE_PIN C12 [get_ports hdi2s]
set_property PACKAGE_PIN D14 [get_ports hdint]

set_property IOSTANDARD LVCMOS33 [get_ports ext*]
set_property PACKAGE_PIN R2 [get_ports {ext[0]}]
set_property PACKAGE_PIN P4 [get_ports {ext[1]}]
set_property PACKAGE_PIN R1 [get_ports {ext[2]}]
set_property PACKAGE_PIN M5 [get_ports {ext[3]}]
set_property PACKAGE_PIN P1 [get_ports {ext[4]}]
set_property PACKAGE_PIN N4 [get_ports {ext[5]}]
set_property PACKAGE_PIN N2 [get_ports {ext[6]}]
set_property PACKAGE_PIN N3 [get_ports {ext[7]}]
set_property PACKAGE_PIN N1 [get_ports {ext[8]}]
set_property PACKAGE_PIN M4 [get_ports {ext[9]}]
set_property PACKAGE_PIN M2 [get_ports {ext[10]}]
set_property PACKAGE_PIN M1 [get_ports {ext[11]}]

set_property IOSTANDARD LVCMOS33 [get_ports ad*]
set_property PACKAGE_PIN P14 [get_ports adreset]
set_property PACKAGE_PIN R5 [get_ports {addat[0]}]
set_property PACKAGE_PIN T5 [get_ports {addat[1]}]
set_property PACKAGE_PIN R6 [get_ports {addat[2]}]
set_property PACKAGE_PIN R7 [get_ports {addat[3]}]
set_property PACKAGE_PIN T7 [get_ports {addat[4]}]
set_property PACKAGE_PIN R8 [get_ports {addat[5]}]
set_property PACKAGE_PIN T8 [get_ports {addat[6]}]
set_property PACKAGE_PIN T9 [get_ports {addat[7]}]
set_property PACKAGE_PIN T10 [get_ports {addat[8]}]
set_property PACKAGE_PIN R10 [get_ports {addat[9]}]
set_property PACKAGE_PIN R11 [get_ports {addat[10]}]
set_property PACKAGE_PIN T12 [get_ports {addat[11]}]
set_property PACKAGE_PIN T13 [get_ports {addat[12]}]
set_property PACKAGE_PIN R13 [get_ports {addat[13]}]
set_property PACKAGE_PIN T14 [get_ports {addat[14]}]
set_property PACKAGE_PIN T15 [get_ports {addat[15]}]
set_property PACKAGE_PIN P16 [get_ports {addat[16]}]
set_property PACKAGE_PIN N16 [get_ports {addat[17]}]
set_property PACKAGE_PIN M15 [get_ports {addat[18]}]
set_property PACKAGE_PIN M16 [get_ports {addat[19]}]
set_property PACKAGE_PIN P15 [get_ports adfield]
set_property PACKAGE_PIN R16 [get_ports advs]
set_property PACKAGE_PIN R15 [get_ports adhs]
set_property PACKAGE_PIN N14 [get_ports adclk]
set_property PACKAGE_PIN R12 [get_ports adsfl]

set_property IOSTANDARD LVCMOS25 [get_ports ddr*]
set_property PACKAGE_PIN E6 [get_ports {ddra[8]}]
set_property PACKAGE_PIN B5 [get_ports {ddra[7]}]
set_property PACKAGE_PIN A4 [get_ports {ddra[6]}]
set_property PACKAGE_PIN B4 [get_ports {ddra[5]}]
set_property PACKAGE_PIN A3 [get_ports {ddrdqs[1]}]
set_property PACKAGE_PIN C6 [get_ports {ddra[4]}]
set_property PACKAGE_PIN D5 [get_ports {ddra[9]}]
set_property PACKAGE_PIN C3 [get_ports {ddra[11]}]
set_property PACKAGE_PIN C2 [get_ports {ddrdq[11]}]
set_property PACKAGE_PIN B2 [get_ports {ddrdq[9]}]
set_property PACKAGE_PIN A2 [get_ports {ddrdq[8]}]
set_property PACKAGE_PIN C1 [get_ports {ddrdq[12]}]
set_property PACKAGE_PIN B1 [get_ports {ddrdq[10]}]
set_property PACKAGE_PIN E2 [get_ports {ddrdq[0]}]
set_property PACKAGE_PIN D1 [get_ports {ddrdq[14]}]
set_property PACKAGE_PIN D3 [get_ports {ddrdq[13]}]
set_property PACKAGE_PIN D4 [get_ports {ddrcke}]
set_property PACKAGE_PIN C4 [get_ports {ddra[12]}]
set_property PACKAGE_PIN F5 [get_ports {ddrckn}]
set_property PACKAGE_PIN E5 [get_ports {ddrckp}]
set_property PACKAGE_PIN F4 [get_ports {ddrdm[1]}]
set_property PACKAGE_PIN F2 [get_ports {ddrdq[1]}]
set_property PACKAGE_PIN E1 [get_ports {ddrdq[15]}]
set_property PACKAGE_PIN G5 [get_ports {ddrras}]
set_property PACKAGE_PIN G4 [get_ports {ddrdm[0]}]
set_property PACKAGE_PIN G2 [get_ports {ddrdq[3]}]
set_property PACKAGE_PIN G1 [get_ports {ddrdq[2]}]
set_property PACKAGE_PIN H5 [get_ports {ddrcs}]
set_property PACKAGE_PIN H4 [get_ports {ddrcas}]
set_property PACKAGE_PIN J5 [get_ports {ddra[10]}]
set_property PACKAGE_PIN J4 [get_ports {ddrba[0]}]
set_property PACKAGE_PIN H2 [get_ports {ddrdq[5]}]
set_property PACKAGE_PIN H1 [get_ports {ddrdq[4]}]
set_property PACKAGE_PIN J3 [get_ports {ddrba[1]}]
set_property PACKAGE_PIN H3 [get_ports {ddrwe}]
set_property PACKAGE_PIN K1 [get_ports {ddrdq[7]}]
set_property PACKAGE_PIN J1 [get_ports {ddrdq[6]}]
set_property PACKAGE_PIN L3 [get_ports {ddra[2]}]
set_property PACKAGE_PIN L2 [get_ports {ddra[3]}]
set_property PACKAGE_PIN K3 [get_ports {ddra[0]}]
set_property PACKAGE_PIN K2 [get_ports {ddrdqs[0]}]
set_property PACKAGE_PIN K5 [get_ports {ddra[1]}]

create_clock -name clk -period 10.000 [get_nets clk]
create_clock -name drck -period 20.000 [get_nets -hier drck]

set_output_delay -clock ddrckp__0 0.7 [get_ports {ddra[*] ddrba[*] ddrras ddrcas ddrwe ddrcke ddrcs}]
set_input_delay -clock ddrckp__0 -max 0.7 [get_ports {ddrdq[*]}]
set_input_delay -clock ddrckp__0 -min -0.7 [get_ports {ddrdq[*]}]

set_false_path -from [get_pins rst_reg/C] -to [get_pins hddma0/fifo_i/fifo0/RST]

set_property LOC PLLE2_ADV_X1Y1 [get_cells memphy0/pll]

set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.UNUSEDPIN PULLUP [current_design]
