set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN N11 [get_ports clk]
set_property IOSTANDARD LVCMOS18 [get_ports led*]
set_property PACKAGE_PIN C16 [get_ports led0]
set_property PACKAGE_PIN D15 [get_ports led1]
set_property PACKAGE_PIN D16 [get_ports led2]
set_property PACKAGE_PIN E16 [get_ports led3]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.UNUSEDPIN PULLUP [current_design]
